# Generated by Django 2.2.5 on 2021-10-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20211013_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
