# Generated by Django 2.2.5 on 2021-10-13 13:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='post',
            name='likers',
            field=models.ManyToManyField(null=True, related_name='like_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
